server:
  port: 8762
spring:
  application:
    name: eureka-server
  boot:
    admin:
      client:
        url: http://localhost:8000
eureka:
  instance:
    hostname: zone1-peer2
    preferIpAddress: false
    metadataMap.zone: zone1
  client:
    register-with-eureka: true
    fetch-registry: true
    region: region-east
    service-url:
      zone1: http://zone1-peer1:8761/eureka/,http://zone1-peer2:8762/eureka/
      zone2: http://localhost:8763/eureka/,http://localhost:8764/eureka/
    availability-zones:
      region-east: zone1,zone2
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: false