feign:
  compression:
    response:
      enabled: true #response设置GZIP压缩
    request:
      enabled: true #request设置GZIP压缩
      mime-types: text/xml,application/xml,application/json #支持压缩的类型
      min-request-size: 2048 #压缩文件的下限
  httpclient:
    enabled: false #是否使用httpClient
  okhttp:
    enabled: true #是否使用okhttp
  hystrix:
    enabled: true #是否使用hystrix
server:
  port: 8010
spring:
  application:
    name: feign-client
  boot:
    admin:
      client:
        url: http://localhost:8000
  main:
    allow-bean-definition-overriding: true #是否允许bean重名
eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
data-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #负载均衡策略
    ConnectTimeout: 3000
    ReadTimeout: 60000
    MaxAutoRetries: 1 #对第一次请求的服务的重试次数
    MaxAutoRetriesNextServer: 1 #要重试的下一个服务的最大数量（不包括第一个服务）
    OkToRetryOnAllOperations: true
circuitBreaker:
  requestVolumeThreshold: 1
  errorThresholdPercentage: 100